packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.25.1
  "eslint-config-next": "15.3.2"
  prettier: ^3.5.3
  tailwindcss: ^4
  "@tailwindcss/postcss": "^4"
  typescript: ^5.8.3

  # Misc
  zod: ^3.24.3

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": 11.1.2
  "@trpc/tanstack-react-query": 11.1.2
  "@trpc/server": 11.1.2

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4

onlyBuiltDependencies:
  - esbuild
